Update to v0.35.2

diff --git a/src/install/on-x-symbolic-link-test b/src/install/on-x-symbolic-link-test
--- a/src/install/on-x-symbolic-link-test
+++ b/src/install/on-x-symbolic-link-test
@@ -1,7 +1,31 @@
 #! /bin/sh -
+
 #
-# For the copyright information for this file, please search up the
-# directory tree for the first COPYING file.
+# Copyright (C) 2012-2023 Stealth Software Technologies, Inc.
+#
+# Permission is hereby granted, free of charge, to any person
+# obtaining a copy of this software and associated documentation
+# files (the "Software"), to deal in the Software without
+# restriction, including without limitation the rights to use,
+# copy, modify, merge, publish, distribute, sublicense, and/or
+# sell copies of the Software, and to permit persons to whom the
+# Software is furnished to do so, subject to the following
+# conditions:
+#
+# The above copyright notice and this permission notice (including
+# the next paragraph) shall be included in all copies or
+# substantial portions of the Software.
+#
+# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
+# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
+# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
+# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
+# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
+# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
+# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
+# OTHER DEALINGS IN THE SOFTWARE.
+#
+# SPDX-License-Identifier: MIT
 #
 
 #
@@ -41,32 +65,41 @@
 # is only performed when installing from a repository, as distribution
 # archives flatten symbolic links, which avoids any problems.
 #
-# Technically we could avoid symbolic links entirely by keeping them
-# flattened in the repository, but this would cause some difficulties
-# regarding keeping the copies in sync. It seems like a poor tradeoff.
-# It's better to just refrain from doing development work in strange
-# environments.
+# Technically we could avoid all symbolic link problems by simply never
+# using symbolic links, but this would make some aspects of development
+# work extremely tedious and error-prone. It's best to simply refrain
+# from doing development work in strange environments.
 #
 
-argv0=$1
-case $argv0 in
-  '' | */ | *'
-')
-    cat >&2 <<'EOF'
-argv0 is insane.
-EOF
-    exit 1
-  ;;
-  /*)
-  ;;
-  *)
-    argv0=./$argv0
-  ;;
+case $# in 0)
+  printf '%s\n' "Invalid argument count: 0" >&2
+  exit 1
 esac
+
+argv0=$1
+argv0_is_invalid=false
+case $argv0 in *[!/0-9A-Z_a-z-]* | install/*/*)
+  argv0_is_invalid=:
+;; install/on-[0-9A-Za-z]*[0-9A-Za-z])
+  :
+;; *)
+  argv0_is_invalid=:
+esac
+if $argv0_is_invalid; then
+  sed '
+    s/'\''/&\\&&/g
+    1 s/^/Invalid initial argument: '\''/
+    $ s/$/'\''/
+  ' <<EOF >&2
+$argv0
+EOF
+  exit 1
+fi
 readonly argv0
+readonly argv0_is_invalid
 shift
 
-on_x=`basename "$argv0"` || exit $?
+on_x=`basename $argv0` || exit $?
 readonly on_x
 export on_x
 
@@ -204,18 +237,11 @@ EOF
 fi
 
 #-----------------------------------------------------------------------
+# Run the next script
+#-----------------------------------------------------------------------
 
-#
-# The GNU Autoconf manual suggests avoiding "$@" when $# is zero to be
-# as portable as possible. This is probably never a problem these days,
-# but let's do it anyway.
-#
-
-case $# in
-  0)
-    $next
-  ;;
-  *)
-    $next "$@"
-  ;;
+case $# in 0)
+  exec $next
+;; *)
+  exec $next "$@"
 esac
